### ISSUE TITLE
i18next is not exported and assumed global variable

### ISSUE THREAD

**Issue by tpluscode** [colscott/lit-i18n#10]
The readme and `index.js` states that `in18next` should be exported but it's not.

It is used as global, which requires calling code to set `window.i18next = i18next` somewhere at page load

Is that how it's supposed to work?

**Comment by colscott** [comment]
Hi, i18next is assumed a peer dependency and is marked so in the package.json. And you're right it is assumed it is a global.
It used to have i18next as a direct dependency but that caused other issues.

I'll correct the the index.js to reinstate the export, thanks for pointing it out. For now you can also use i18next as a global rather than trying to use the export.

Let me know if there are any issues with the global approach.

**Comment by tpluscode** [comment]
No, works well in general, thanks 👌

**Comment by colscott** [comment]
Reviewed the code history. I should have removed the export in commit 640fe245b6928b46eb1b39429228ece75a497b39 but it looks like it was missed.

I've removed it and updated the readme. Thanks for spotting this!
